# @file makefile
# @author Dmitry Krysin
# @date 2010
# @brief build Makefile

# имя
NAME	?= apaf

INCLUDE ?=
SFILES	?=
FLAGS ?= 

SFILES	+= apaf.c
SFILES	+= apaf_menu.c
SFILES	+= apaf1.c
SFILES	+= apaf2.c
SFILES	+= apaf3.c
SFILES	+= apaf4.c
SFILES	+= apaf5.c
SFILES	+= apaf6.c
SFILES	+= apaf7.c
SFILES	+= apaf8.c
SFILES	+= apaf9.c
SFILES	+= apaf10.c
SFILES	+= apaf11.c
SFILES	+= apaf12.c
SFILES	+= apaf13.c
SFILES	+= apaf14.c
SFILES	+= apaf15.c
SFILES	+= apaf16.c
SFILES	+= apaf17.c
SFILES	+= apaf18.c
SFILES	+= apaf19.c
SFILES	+= apaf20.c
SFILES	+= apaf21.c
SFILES += apaf22.c
SFILES += apaf23.c

OUTFILE	= bin/$(NAME)

#------------------------------------------------------------
# Default
all: build

# Build
build: 
	g++ $(FLAGS) $(SFILES) $(INCLUDE) -o $(OUTFILE)
#
